# Generated by Django 4.2 on 2023-04-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attachment",
            old_name="decription",
            new_name="description",
        ),
    ]
